services:
  fic-grades-bot:
    build: .
    container_name: fic-bot
    restart: always
    env_file:
      - .env
    environment:
      - DB_PATH=/data/bot.db
    volumes:
      - fic_grades_data:/data

volumes:
  fic_grades_data:
